name: Run Postman Tests

on:
  push:
    branches:
      - master  # or main, or any other branch you want to monitor

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # specify your Node.js version

    - name: Install dependencies
      run: npm install -g newman newman-reporter-html

    - name: Run Postman Collection
      run: |
        newman run your-collection.json -r html --reporter-html-export newman-report.html

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman-report.html
